version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-frontend:
    docker:
      - image: cimg/node:16.14
    resource_class: small
    working_directory: ~/racetrack/frontend
    steps:
      - checkout:
          path: ~/racetrack
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test-unit
  build-api:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    working_directory: ~/racetrack/api
    steps:
      - checkout:
          path: ~/racetrack
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Lint
          command: python3 -m black --check ./src/
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Prepare integration test services
          command: |
            cd ..

            docker create -v /app-data --name data alpine:3.4 /bin/true
            docker cp . data:/app-data

            docker-compose -f integration-test.yaml up --build --detach
            sleep 15
      - run:
          name: Run integration tests
          command: docker exec -it $(docker ps | grep frontend | awk '{print $1}') sh -c "npm run test-integration"

workflows:
  build:
    jobs:
      - build-frontend
      - build-api
